frontend:
  base-url: ${FRONTEND_BASE_URL:http://localhost:3000}
  auth-code-redirect-uri: ${AUTH_CODE_REDIRECT_URI:/oauth2/code}
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: ${BASE_URL}/login/oauth2/code/google
          naver:
            client-id: ${NAVER_OAUTH2_CLIENT_ID}
            client-secret: ${NAVER_OAUTH2_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-name: Naver
            redirect-uri: ${BASE_URL}/login/oauth2/code/naver
            scope: profile,email
          kakao:
            client-id: ${KAKAO_OAUTH2_CLIENT_ID}
            client-secret: ${KAKAO_OAUTH2_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            redirect-uri: ${BASE_URL}/login/oauth2/code/kakao
            scope: openid,account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            issuer-uri: https://kauth.kakao.com
