== 이슈 관련 API

=== 이슈 생성

operation::core-api/append-issue[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 이슈 상세 조회

operation::core-api/find-issue[snippets='http-request,path-parameters,http-response,response-fields']

=== 이슈 이름 수정

operation::core-api/modify-issue-name[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 이슈 내용 수정

operation::core-api/modify-issue-content[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 이슈 담당자 수정

operation::core-api/modify-issue-assignee[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 이슈 컴포넌트 수정

operation::core-api/modify-issue-component[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 이슈 비즈포인트 수정

operation::core-api/modify-issue-bizpoint[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 이슈 중요도 수정

operation::core-api/modify-issue-importance[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 이슈 에픽 수정

operation::core-api/modify-issue-epic[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 이슈 진행 상태 수정

operation::core-api/modify-issue-status[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 에픽 하위 이슈 목록 조회

operation::core-api/find-epic-issues[snippets='http-request,path-parameters,http-response,response-fields']

=== 스프린트 하위 이슈 목록 조회

operation::core-api/find-sprint-issues[snippets='http-request,path-parameters,http-response,response-fields']

=== 컴포넌트 별 활성 스프린트 이슈 목록 조회

operation::core-api/find-component-issues[snippets='http-request,path-parameters,http-response,response-fields']

=== 스프린트 내 이슈 이동

operation::core-api/modify-issue-sprint[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 나의 이슈 목록 조회

operation::core-api/find-my-issues[snippets='http-request,query-parameters,http-response,response-fields']

=== 이슈 삭제

operation::core-api/delete-issue[snippets='http-request,path-parameters,http-response,response-fields']